Repository GDSC-KNU/3rd-sc-ex2-GamzaMap-Frontend, pull requests merged in 2024-02, with the labels that each got.

#9 Feat/마이 페이지 디자인
  .gitignore
  package-lock.json
  package.json
  src/assets/image1.svg
  src/assets/image2.svg
  src/assets/image3.svg
  src/assets/image4.svg
  src/assets/imageEdit.svg
  src/assets/myPageProfile.svg
  src/components/organisms/EditProfile/BussinessNumber.jsx
  src/components/organisms/EditProfile/CheckBossForm.jsx
  src/components/organisms/EditProfile/EditProfileIndex.jsx
  src/components/organisms/EditProfile/InteractionButton.jsx
  src/components/organisms/EditProfile/ProfileBox.jsx
  src/components/organisms/EditProfile/ProfileDetail.jsx
  src/components/organisms/EditProfile/QuestionOwner.jsx
  src/components/organisms/EditProfile/SelectedImages.jsx
  src/components/organisms/EditProfile/ShopNameInput.jsx
  src/components/organisms/EditProfile/ShowLocation.jsx
  src/components/organisms/EditProfile/index.jsx
  src/components/template/BossTemplate.jsx
  src/components/template/EditProfileTemplate.jsx
  src/components/template/InfoTemplate.jsx
  src/pages/CheckBossPage.jsx
  src/utils/router.jsx
Labels: ✨ feat, 🎨 style, ⚒️ refactor

#15 Feat/sidebar
  index.html
  package-lock.json
  package.json
  src/assets/Sidebar/Chatting-Icon.svg
  src/assets/Sidebar/Map-Icon.svg
  src/assets/Sidebar/Pick-Icon.svg
  src/components/organisms/Sidebar/Buttons.jsx
  src/components/organisms/layout/Sidebar.jsx
  src/components/template/MapTemplate.jsx
  src/pages/Map.jsx
  src/styles/SidebarStyle.jsx
  src/utils/router.jsx
  vite.config.js
Labels: ✨ feat, 🎨 style

#16 기본적인 Setting 변경
  index.html
  public/PotatoIcon.png
  public/gamzaIcon.ico
Labels: ✨ feat

#17 Header 구현
  src/assets/Header/LoginButton.svg
  src/assets/Header/Store.svg
  src/assets/Header/UserProfileImg.svg
  src/assets/Header/coffee.svg
  src/assets/Header/gas.svg
  src/assets/Header/restaurant.svg
  src/components/common/Button/HeaderButtons.jsx
  src/components/common/Button/LoginButton.jsx
  src/components/common/Button/LogoButton.jsx
  src/components/common/Input/SearchInput.jsx
  src/components/organisms/layout/Header.jsx
  src/styles/HeaderStyle.jsx
Labels: ✨ feat, 🎨 style

#18 기타 세팅
  .eslintrc.cjs
  .prettierrc.json
Labels: 🎨 style

#19 HomePage
  src/assets/HomePage/HomeArrow.svg
  src/assets/HomePage/gamzaIcon.svg
  src/components/organisms/Home/TextContainer.jsx
  src/components/organisms/layout/Sidebar.jsx
  src/components/template/HomeTemplate.jsx
  src/styles/ContentStyle.jsx
  src/styles/HomeStyle.jsx
  src/styles/SidebarStyle.jsx
Labels: ✨ feat, 🎨 style

#20 LoginPage
  src/assets/KakaoLogo.svg
  src/components/common/Button/LoginButton.jsx
  src/components/common/Input/LoginInput.jsx
  src/components/organisms/Login/Buttons.jsx
  src/components/organisms/Login/LoginText.jsx
  src/components/organisms/Login/Title.jsx
  src/components/template/LoginTemplate.jsx
  src/styles/LoginStyle.jsx
Labels: ✨ feat, 🎨 style

#21 PickPage
  src/assets/Pick/EmptyStarImage.svg
  src/assets/Pick/FillStarImage.svg
  src/assets/Pick/PickPicture.png
  src/components/organisms/Pick/ChatRoom.jsx
  src/components/organisms/Pick/index.jsx
  src/components/template/PickTemplate.jsx
  src/pages/pick.jsx
  src/styles/ContentStyle.jsx
  src/styles/PickStyle.jsx
Labels: ✨ feat, 🎨 style

#23 PickPage
  index.html
Labels: 🎨 style

#24 StoreDetail Page
  src/assets/StoreDetail/DotImg.svg
  src/assets/StoreDetail/EmptyStarImage.svg
  src/assets/StoreDetail/FillStarImage.svg
  src/assets/StoreDetail/KEANU.png
  src/components/organisms/StoreDetail/Info.jsx
  src/components/organisms/StoreDetail/StoreContent.jsx
  src/components/template/StoreDetailTemplate.jsx
  src/pages/StoreDetail.jsx
  src/styles/StoreDetailStyle.jsx
  src/utils/router.jsx
Labels: ✨ feat, good first issue, 🎨 style

#27 Build시 오류 수정
  src/components/common/Button/HeaderButtons.jsx
Labels: 🤬 bug

#28 1차 Bug Fix
  src/components/common/Button/HeaderButtons.jsx
Labels: 🤬 bug

#29 Loginpage 기능구현
  package-lock.json
  package.json
  src/components/common/Input/LoginInput.jsx
  src/components/organisms/Login/Buttons.jsx
  src/main.jsx
  src/store/login-action.js
  src/store/login-slice.js
  src/store/register-slice.js
  src/store/store.js
  src/styles/LoginStyle.jsx
  src/utils/URL.jsx
  vite.config.js
Labels: 🤬 bug, ✨ feat, ❌ wontfix

#31 [Fix]: gamzaIcon 경로 수정
  src/components/organisms/Chatting/ChatState.jsx
Labels: 🤬 bug

#34 DetailPage 기능 구현
  package-lock.json
  src/assets/Detail/Baek-So-Jeong-Detail.png
  src/assets/Detail/Cafe-Concrete-Detail.png
  src/assets/Detail/Cafe-Keanu-Detail.png
  src/assets/Detail/Goni-Table-Detail.png
  src/assets/Detail/Myeon-Tamjeong-Detail.png
  src/assets/Detail/W-Collection-Detail.png
  src/assets/Pick/Baek-So-Jeong.png
  src/assets/Pick/Cafe-Concrete.png
  src/assets/Pick/Cafe-Keanu.png
  src/assets/Pick/Goni-Table.png
  src/assets/Pick/Myeon-Tamjeong.png
  src/assets/Pick/W-Collection.png
  src/components/organisms/Chatting/ChattingRoom.jsx
  src/components/organisms/Map/Map.jsx
  src/components/organisms/Map/MapOption.jsx
  src/components/organisms/Pick/ChatRoom.jsx
  src/components/organisms/StoreDetail/Info.jsx
  src/components/organisms/StoreDetail/StoreContent.jsx
  src/components/template/LoadingTemplate.jsx
  src/components/template/PickTemplate.jsx
  src/components/template/StoreDetailTemplate.jsx
  src/styles/StoreDetailStyle.jsx
  src/utils/StoreInfo.js
  src/utils/router.jsx
Labels: ✨ feat

#35 DetailPage 구현
  package-lock.json
  src/assets/Detail/Baek-So-Jeong-Detail.png
  src/assets/Detail/Cafe-Concrete-Detail.png
  src/assets/Detail/Cafe-Keanu-Detail.png
  src/assets/Detail/Goni-Table-Detail.png
  src/assets/Detail/Myeon-Tamjeong-Detail.png
  src/assets/Detail/W-Collection-Detail.png
  src/assets/Pick/Baek-So-Jeong.png
  src/assets/Pick/Cafe-Concrete.png
  src/assets/Pick/Cafe-Keanu.png
  src/assets/Pick/Goni-Table.png
  src/assets/Pick/Myeon-Tamjeong.png
  src/assets/Pick/W-Collection.png
  src/components/organisms/Chatting/ChattingRoom.jsx
  src/components/organisms/Map/Map.jsx
  src/components/organisms/Map/MapOption.jsx
  src/components/organisms/Pick/ChatRoom.jsx
  src/components/organisms/StoreDetail/Info.jsx
  src/components/organisms/StoreDetail/StoreContent.jsx
  src/components/template/LoadingTemplate.jsx
  src/components/template/PickTemplate.jsx
  src/components/template/StoreDetailTemplate.jsx
  src/styles/StoreDetailStyle.jsx
  src/utils/StoreInfo.js
  src/utils/router.jsx
Labels: ✨ feat
