Repository GDSC-KNU/3rd-sc-ex2-GamzaMap-Frontend, pull requests merged in 2024-01, with the labels that each got.

#1 Feat/Header
  index.html
  package-lock.json
  package.json
  public/PotatoIcon.png
  src/assets/coffee.svg
  src/assets/gas.svg
  src/assets/profile.svg
  src/assets/restaurant.svg
  src/assets/search.svg
  src/components/common/Button/HeaderButtons.jsx
  src/components/common/Button/LogoButton.jsx
  src/components/common/Button/ProfileButton.jsx
  src/components/common/Input/RegisterButton.jsx
  src/components/common/Input/SearchInput.jsx
  src/components/organisms/layout/Header.jsx
  src/components/template/HomeTemplate.jsx
  src/pages/Home.jsx
  tailwind.config.js
Labels: ✨ feat, 🎨 style

#8 Fix/prettier
  .prettierrc.json
Labels: 🤬 bug, 🚨 HOTFIX

#7 Tailwind 커스텀 세팅 부분 수정중
  tailwind.config.js
Labels: 🤬 bug, 🎨 style
